---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 55.5.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    prometheus:
      ingress:
        enabled: true
        ingressClassName: internal
        hosts:
          - prometheus.${SECRET_DOMAIN}
    grafana:
      enabled: false # We'll deploy Grafana separately
